version: '3'

services:
  postgresql:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
